<?php

namespace InnDigit\Components\Quiz;

class Constants
{
    public static $image_urls = [
        'finansije_oblast_f' => PLUGIN_URL . 'assets/icons/finansije.svg',
        'marketing_oblast_m' => PLUGIN_URL . 'assets/icons/marketing.svg',
        'ljudski_resursi_oblast_h' => PLUGIN_URL . 'assets/icons/human-resources.svg',
        'strategija_oblast_s' => PLUGIN_URL . 'assets/icons/strategija.svg',
        'proces_oblast_p' => PLUGIN_URL . 'assets/icons/proces.svg',
        'kontakt_oblast_k' => PLUGIN_URL . 'assets/icons/kontakt.svg',
    ];

    public static $specs = [
        'spec1' => 'Izazovi koji stoje pred prerađivačkom industrijom naše zemlje u oblasti digitalizacije poslovanja su veliki, međutim oblasti kao što su prerada drveta i metala su prepoznate kao ključna područja intervencije najvećeg broja akcija podrške provedenih na temu digitalizacije. Stoga, ne posustajte, ukoliko se osvrnete oko sebe postoje organizacije i institucije koje će vam pomoći u tranziciji ka novim tehnologijama i modelima poslovanja. Vaša prva kontakt tačka je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec2' => 'Energetski sektor je u našoj zemlji uvijek bio nosilac razvoja pa tu ulogu nosi i u eri digitalizacije poslovanja. Stoga, zauzmite stav lidera i upustite se u nove poduhvate te motivišite i ostale privredne subjekte da se oslone na Vaš primjer i da Vas slijede ka održivoj budućnosti. Vaš osnovni partner u ovom izazovu je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec3' => 'Finansijski sektor je jedan od stubova razvoja pa tu ulogu nosi i u eri digitalizacije poslovanja. Stoga, angažujte maksimalne resurse, upustite se u nove poduhvate te motivišite i podržite projekte naših privrednih subjekata koji žele da provode digitalnu transformaciju. Vaš najjači partner u ovom izazovu je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec4' => 'Građevinarstvo je, to vidimo svuda oko nas, pod uticajem digitalizacije našeg društva. Zgrade su sve pametnije, pa budite i Vi. Uzmite alat i uhvatite se u koštac sa novom transformacijom. Vaš najjači partner u ovom izazovu je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec5' => 'Naša privreda treba podršku u procesu digitalne transformacije, a to im najbolje može pružiti domaća IKT industrija. Stoga, angažujete svoje kapacitete i kreativnost na projektima naših preduzeća i budite im najveća podrška u težnji ka održivom poslovanju. Centar za digitalnu transformaciju Privredne komore već treću godinu za redom povezuje potrebe naše privrede i rješenja koja nude IKT stručnjaci sa ovih prostora.',
        'spec6' => 'Komunalne i uslužne djelatnosti su uvijek bile osnovni preduslov za opstanak privrede. Stoga, ostvrnite se još jednom oko sebe, svijet se transformiše a zahtjevi prema vama postaju brži. Vaš partner u novom dobu je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec7' => 'Izazovi koji stoje pred poljoprivredom i proizvođačima hrane u našoj zemlji u oblasti digitalizacije poslovanja su veliki. Međutim, ove oblasti su i prepoznate kao ključna područja intervencije najvećeg broja akcija podrške provedenih na temu digitalizacije. Stoga, ne posustajte, ukoliko se osvrnete oko sebe postoje organizacije i institucije koje će vam pomoći u tranziciji ka novim tehnologijama i modelima poslovanja. Vaša prva kontakt tačka je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec8' => 'Prilike koje nudi digitalna transformacija sektor saobraćaja i veza mora iskoristiti! Od vašeg angažmana zavisi brzina cijele privrede. Pravi partner u ovom poslu je Centar za digitalnu transformaciju Privredne komore.',
        'spec9' => 'Pred nama je moderan klijent. Zahtjevan i bez mnogo vremena. Zadovoljenje njegovih potreba nije lako. Kako biste mu se prilagodili, digitalna transformacija vašeg poslovanja je neminovna. Vaša prva kontakt tačka je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec10' => 'Pred nama je moderan potrošač. Zahtjevan i bez mnogo vremena. Zadovoljenje njegovih potreba nije lako. Kako biste mu se prilagodili digitalna transformacija vašeg poslovanja je neminovna. Vaša prva kontakt tačka je Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'spec11' => 'Ne postoji organizacija koja nije inovativna, već samo ona koje ne zna prepoznati i iskoristiti ideje. Identifikovati prilike za inovacije i podržati istraživanje i razvoj te stvarati podsticajno okruženje koje uči iz grešaka, nije lako. U tome vam može pomoći <a href="https://dihidemo.org/">digitalni inovacioni hab IDEMO.</a>',
        'spec12' => 'Za bolju informisanost rukovodstva i smanjenje broja grešaka u radu, te bolju komunikaciju unutar kolektiva preduzeće treba da razmotri uvođenje ili ažuriranje ERP rješenja (alat za upravljanje resursima organizacije). U zavisnosti od veličine i složenosti subjekta, ovakva rješenja mogu koštati od 10 hiljada evra pa naviše.',
        'spec13' => 'DMS (rješenja za upravljanje dokumentacijom) omogućava preduzeću da kontroliše tok informacija. Neka besplatna rješenja za skladištenje dokumenata u oblaku i saradnju u stvarnom vremenu su Google Drive, Microsoft OneDrive i drugi. S obzirom da ove opcije imaju ograničenja po pitanju prostora, potrebno jer istražiti plaćene platforme sa kompletnijom ponudom ili izraditi namjenski softver.',
        'spec14' => 'Izrada kvalitetne internet stranice i strategije za digitalni marketing će unaprijediti kvalitet ponude i odnose s kupcima, te ojačati brend a zatim i povećati prodaju. Na našem tržištu djeluje veliki broj manjih i većih agencija za marketing među kojima se sigurno nalazi i ona koja odgovara vašim zahtjevima.',
        'spec15' => 'U saradnji sa Jedinicom za visokotehnološki kriminalitet Ministarstva unutrašnjih poslova Republike Srpske, Privredna komora informiše i edukuje privredne subjekte o sajber kriminalu i značaju zaštite. Ove institucije vam stoje na raspolaganju za savjete u vezi sa rješenjima za zaštitu vaših digitalnih alata i poslovanja uopšte.',
        'spec16' => 'S obzirom da ne koristite digitalne alate u poslovanju, potrebno je da se upoznate sa prednostima i prijetnjama koje preduzeću donosi digitalna transformacija. Ovo je zadatak kojem je potrebno pristupiti strateški i sistematizovano. Centar za digitalnu transformaciju PK RS je jedinstvena institucija koja u Srpskoj nudi sveobuhvatne savjetodavne usluge i metodologiju za digitalnu transformaciju privrednih subjekata.',
        'spec17' => 'Iako je broj elektronskih usluga organa uprave koje imamo na raspolaganju mali, korišćenje ovih alata vam može uštediti vrijeme i smanjiti broj grešaka u radu. Potrebno je da uložite malo vremena za informisanje o raspoloživim servisima poreskih uprava i/ili banke, te malo više za obuku za korišćenje tih servisa, ali ćete zato smanjiti broj posjeta ovim organizacijama i ostaće vam više vremena za neke složenije operacije. Stoga, posjetite internet stranice nadležnih institucija prije nego odete lično "da nosite papire".',
        'spec19' => 'Automatizacija procesa u poslovanju povećava efikasnost i smanjuje troškove! Ovo se postiže upotrebom rješenja kao što su BPM (Business Process Management) platforme, RPA (Robotic Process Automation) softveri i ERP (Enterprise Resource Planning) sistemi. Ovi alati omogućavaju automatsko izvršavanje rutinskih zadataka, optimizaciju tokova rada i integrisanje različitih poslovnih funkcija. Kad izradite svoju mapu puta za digitalnu transformaciju (uz podršku Centra za digitalnu transformaciju Privredne komore Republike Srpske) i uvedete odgovarajuće rješenje za upravljanje poslovanjem, povećaćete produktivnost, smanjiti broj grešaka, bolje upravljati resursima i lakše odlučivati.',
        'spec20' => 'Korišćenje CAD (kompjuterskog dizajniranje) u kombinaciji s 3D skenerima i štampačima pruža niz prednosti u procesu prototipovanja. CAD omogućava precizno modeliranje i dizajniranje prototipa, te zajedno s 3D štampačima omogućava automatsku proizvodnju fizičkih prototipa na osnovu digitalnih modela, što ubrzava razvoj proizvoda, smanjuje troškove proizvodnje i omogućava lakše testiranje i iteraciju dizajna prije konačne implementacije. Mašinski fakultet u Banjaluci nudi usluge 3D skeniranja i štampanja, kao i obuke za korišćenje CAD rješenja.',
        'spec21' => 'Komorski sistem Republike Srpske godišnje organizuje više od 50 informativnih i edukativnih događaja širom Srpske ili onlajn. Preovladavaju događaji na kojima je učešće besplatno. Članovi mogu u svakom trenutku da kontaktiraju Komoru i iniciraju edukacije na teme koje su korisne za djelatnost ili cijelu privredu. Više informacija nađite na <a href="https://edukacije.komorars.ba/">edukacije.komorars.ba</a>',
        'spec22' => 'Podaci koje preduzeće prikuplja od klijenata su osnova za personalizaciju usluga i proizvoda i unapređenje korisničkog iskustva. Budite oprezni, morate poštovati regulativu o privatnosti. U BiH, Agencija za zaštitu ličnih podataka je nadležna za provođenje Zakona o zaštiti ličnih podataka.',
        'spec23' => 'Digitalizacija poslovanja i digitalna transformacija više nemaju alternativu. Vlada Republike Srpske i međunarodni donatori su pokrenuli niz aktivnosti na unapređenju uslova poslovanja i pružanju tehničke i finansijske podrške digitalnoj transformaciji privrede. Informacije o svim dostupnim programima podrške možete naći na platformi Privredne komore Republike Srpske: <a href="https://infobiz.komorars.ba/">infobiz.komorars.ba</a>',
        'spec24' => 'Proces digitalne transformacije privrede zahtjeva strateški pristup, kako u analizi trenutne situacije, tako i u planiranju budućih aktivnosti, odnosno kreiranju digitalne strategije i pronalaženju optimalnih digitalnih rješenja na tržištu u skladu sa potrebama preduzeća. Centar za digitalnu transformaciju Privredne komore Republike Srpske pruža sveobuhvatnu podršku preduzećima na polju digitalne transformacije.',
    ];

    public static $points = [
        'finansije_oblast_f' => 16,
        'marketing_oblast_m' => 22,
        'ljudski_resursi_oblast_h' => 10,
        'strategija_oblast_s' => 101,
        'proces_oblast_p' => 74
    ];

}
