<?php

namespace InnDigit\Components\Acf;

class Fields
{
	public function __construct()
	{
		add_action('acf/include_fields', [&$this, 'register']);
	}

	public static function register()
	{
		acf_add_local_field_group(array(
			'key' => 'group_65da583e60df8',
			'title' => 'InnDigitALAT',
			'fields' => array(
				array(
					'key' => 'field_65da58403b6aa',
					'label' => 'KONTAKT (oblast K)',
					'name' => 'kontakt_oblast_k',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'row',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65da5e85afa25',
							'label' => 'Naziv privrednog društva:',
							'name' => 'naziv_privrednog_drustva',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da5dfc44dc8',
							'label' => 'Djelatnost (odaberite od ponuđenih):',
							'name' => 'djelatnost_odaberite_od_ponudenih',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Drvna industrija i šumarstvo' => 'Drvna industrija i šumarstvo',
								'Elektro-hemijska industrija' => 'Elektro-hemijska industrija',
								'Energetika' => 'Energetika',
								'Finansijske djelatnosti i osiguranje' => 'Finansijske djelatnosti i osiguranje',
								'Građevinarstvo' => 'Građevinarstvo',
								'Štampanje' => 'Štampanje',
								'Informaciono-komunikacione tehnologije' => 'Informaciono-komunikacione tehnologije',
								'Komunalne i uslužne djelatnosti' => 'Komunalne i uslužne djelatnosti',
								'Metalurgija i prerada metala' => 'Metalurgija i prerada metala',
								'Poljoprivreda, ribarstvo, prehrambena i duvanska industrija' => 'Poljoprivreda, ribarstvo, prehrambena i duvanska industrija',
								'Saobraćaj i veze' => 'Saobraćaj i veze',
								'Industrija tekstila, kože i obuće' => 'Industrija tekstila, kože i obuće',
								'Trgovina' => 'Trgovina',
								'Turizam i ugostiteljstvo' => 'Turizam i ugostiteljstvo',
								'Ostalo' => 'Ostalo',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da5f0961065',
							'label' => 'Sjedište (odaberite od ponuđenih):',
							'name' => 'sjediste_odaberite_od_ponudenih',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Banja Luka' => 'Banja Luka',
								'Berkovići' => 'Berkovići',
								'Bijeljina' => 'Bijeljina',
								'Bileća' => 'Bileća',
								'Bratunac' => 'Bratunac',
								'Brod' => 'Brod',
								'Derventa' => 'Derventa',
								'Doboj' => 'Doboj',
								'Donji Žabar' => 'Donji Žabar',
								'Foča' => 'Foča',
								'Gacko' => 'Gacko',
								'Gradiška' => 'Gradiška',
								'Han Pijesak' => 'Han Pijesak',
								'Istočna Ilidža' => 'Istočna Ilidža',
								'Istočni Drvar' => 'Istočni Drvar',
								'Istočni Mostar' => 'Istočni Mostar',
								'Istočni Stari Grad' => 'Istočni Stari Grad',
								'Istočno Novo Sarajevo' => 'Istočno Novo Sarajevo',
								'Istočno Sarajevo' => 'Istočno Sarajevo',
								'Jezero' => 'Jezero',
								'Kalinovik' => 'Kalinovik',
								'Kneževo' => 'Kneževo',
								'Kostajnica' => 'Kostajnica',
								'Kotor Varoš' => 'Kotor Varoš',
								'Kozarska Dubica' => 'Kozarska Dubica',
								'Krupa na Uni' => 'Krupa na Uni',
								'Kupres' => 'Kupres',
								'Laktaši' => 'Laktaši',
								'Ljubinje' => 'Ljubinje',
								'Lopare' => 'Lopare',
								'Milići' => 'Milići',
								'Modriča' => 'Modriča',
								'Mrkonjić Grad' => 'Mrkonjić Grad',
								'Nevesinje' => 'Nevesinje',
								'Novi Grad' => 'Novi Grad',
								'Novo Goražde' => 'Novo Goražde',
								'Osmaci' => 'Osmaci',
								'Oštra Luka' => 'Oštra Luka',
								'Pale' => 'Pale',
								'Pelagićevo' => 'Pelagićevo',
								'Petrovac' => 'Petrovac',
								'Petrovo' => 'Petrovo',
								'Prijedor' => 'Prijedor',
								'Prnjavor' => 'Prnjavor',
								'Ribnik' => 'Ribnik',
								'Rogatica' => 'Rogatica',
								'Rudo' => 'Rudo',
								'Sokolac' => 'Sokolac',
								'Srbac' => 'Srbac',
								'Srebrenica' => 'Srebrenica',
								'Stanari' => 'Stanari',
								'Teslić' => 'Teslić',
								'Trebinje' => 'Trebinje',
								'Trnovo' => 'Trnovo',
								'Ugljevik' => 'Ugljevik',
								'Višegrad' => 'Višegrad',
								'Vlasenica' => 'Vlasenica',
								'Vukosavlje' => 'Vukosavlje',
								'Zvornik' => 'Zvornik',
								'Čajniče' => 'Čajniče',
								'Čelinac' => 'Čelinac',
								'Šamac' => 'Šamac',
								'Šekovići' => 'Šekovići',
								'Šipovo' => 'Šipovo'
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da5f8558713',
							'label' => 'Veličina privrednog društva (odaberite od ponuđenih):',
							'name' => 'velicina_privrednog_drustva_odaberite_od_ponudenih',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Malo' => 'Malo',
								'Srednje' => 'Srednje',
								'Veliko' => 'Veliko',
							),
							'default_value' => '',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da601887e1b',
							'label' => 'Godina osnivanja kompanije (odaberite od ponuđenih):',
							'name' => 'godina_osnivanja_kompanije_odaberite_od_ponudenih',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								2024 => '2024',
								2023 => '2023',
								2022 => '2022',
								2021 => '2021',
								2020 => '2020',
								2019 => '2019',
								2018 => '2018',
								2017 => '2017',
								2016 => '2016',
								2015 => '2015',
								2014 => '2014',
								2013 => '2013',
								2012 => '2012',
								2011 => '2011',
								2010 => '2010',
								2009 => '2009',
								2008 => '2008',
								2007 => '2007',
								2006 => '2006',
								2005 => '2005',
								2004 => '2004',
								2003 => '2003',
								2002 => '2002',
								2001 => '2001',
								2000 => '2000',
								1999 => '1999',
								1998 => '1998',
								1997 => '1997',
								1996 => '1996',
								1995 => '1995',
								1994 => '1994',
								1993 => '1993',
								1992 => '1992',
								1991 => '1991',
								1990 => '1990',
								1989 => '1989',
								1988 => '1988',
								1987 => '1987',
								1986 => '1986',
								1985 => '1985',
								1984 => '1984',
								1983 => '1983',
								1982 => '1982',
								1981 => '1981',
								1980 => '1980',
								1979 => '1979',
								1978 => '1978',
								1977 => '1977',
								1976 => '1976',
								1975 => '1975',
								1974 => '1974',
								1973 => '1973',
								1972 => '1972',
								1971 => '1971',
								1970 => '1970',
								1969 => '1969',
								1968 => '1968',
								1967 => '1967',
								1966 => '1966',
								1965 => '1965',
								1964 => '1964',
								1963 => '1963',
								1962 => '1962',
								1961 => '1961',
								1960 => '1960',
								1959 => '1959',
								1958 => '1958',
								1957 => '1957',
								1956 => '1956',
								1955 => '1955',
								1954 => '1954',
								1953 => '1953',
								1952 => '1952',
								1951 => '1951',
								1950 => '1950',
								1949 => '1949',
								1948 => '1948',
								1947 => '1947',
								1946 => '1946',
								1945 => '1945',
								1944 => '1944',
								1943 => '1943',
								1942 => '1942',
								1941 => '1941',
								1940 => '1940',
								1939 => '1939',
								1938 => '1938',
								1937 => '1937',
								1936 => '1936',
								1935 => '1935',
								1934 => '1934',
								1933 => '1933',
								1932 => '1932',
								1931 => '1931',
								1930 => '1930',
								1929 => '1929',
								1928 => '1928',
								1927 => '1927',
								1926 => '1926',
								1925 => '1925',
								1924 => '1924',
								1923 => '1923',
								1922 => '1922',
								1921 => '1921',
								1920 => '1920',
								1919 => '1919',
								1918 => '1918',
								1917 => '1917',
								1916 => '1916',
								1915 => '1915',
								1914 => '1914',
								1913 => '1913',
								1912 => '1912',
								1911 => '1911',
								1910 => '1910',
								1909 => '1909',
								1908 => '1908',
								1907 => '1907',
								1906 => '1906',
								1905 => '1905',
								1904 => '1904',
								1903 => '1903',
								1902 => '1902',
								1901 => '1901',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da60b54bea5',
							'label' => 'Koja od ponuđenih opcija najbliže opisuje Vašu poziciju u kompaniji (odaberite od ponuđenih): ',
							'name' => 'koja_od_ponudenih_opcija_najblize_opisuje_vasu_poziciju_u_kompaniji_odaberite_od_ponudenih',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Vlasnik' => 'Vlasnik',
								'Direktor' => 'Direktor',
								'Rukovodilac sektora' => 'Rukovodilac sektora',
								'Zaposlenik' => 'Zaposlenik',
								'Konsultant' => 'Konsultant',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da612327511',
							'label' => 'Kontakt e-mail adresa',
							'name' => 'kontakt_e-mail_adresa',
							'aria-label' => '',
							'type' => 'email',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
						array(
							'key' => 'field_65da61d5aa246',
							'label' => '"Podaci koje ste naveli se obrađuju u svrhu istraživanja i dostavljanja Izvještaja o samoprocjeni te radi budućeg kontaktiranja sa članovima Privredne komore. U tom smislu mogu biti korišćena adresa i drugi podaci iz odgovora. Podatke dajete dobrovoljno, ali su nužni da biste dobili Izvještaj o samoprocjeni. Više nađite u Politici privatnosti. Molimo saglasnost za:"',
							'name' => 'podaci_koje_ste_naveli_se_obraduju_u_svrhu_istrazivanja_i_dostavljanja_izvjestaja_o_samoprocjeni_te_radi_buduceg_kontaktiranja_sa_clanovima_privredne_komore_u_tom_smislu_mogu_biti_koriscena_adresa_i_drugi_podaci_iz_odgovora_podatke_dajete_dobrovoljno_ali_su_nuzni_da_biste_dobili_izvjestaj_o_samoprocjeni_vise_nadite_u_politici_privatnosti_molimo_saglasnost_za:',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Saglasan sam',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'parent_repeater' => 'field_65da58403b6aa',
						),
					),
				),
				array(
					'key' => 'field_65da64b22c570',
					'label' => 'STRATEGIJA (oblast S)',
					'name' => 'strategija_oblast_s',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65da6562f85c4',
							'label' => 'Koju/koje od navedenih aktivnosti ste do sada proveli u polju primjene digitalne transformacije u kompaniji? (Možete izabrati jedan ili više odgovora)',
							'name' => 'kojukoje_od_navedenih_aktivnosti_ste_do_sada_proveli_u_polju_primjene_digitalne_transformacije_u_kompaniji_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Izrada analize stanja: prepoznate su oblasti poslovanja koje se mogu unaprijediti digitalizacijom.' => '1',
								'Izrada strateškog plana digitalne transformacije.' => '2',
								'Prilagođavanje poslovnog modela digitalnoj ekonomiji.' => '3',
								'Partnerstva sa drugim kompanijama ili organizacijama radi iskorišćenja novih tehnologija.' => '2',
								'Ulaganje u digitalnu infrastrukturu (oprema i softveri).' => '1',
								'Razvoj i/ili uvođenje novih proizvoda/usluga sa digitalnim elementima.' => '2',
								'Stvaranje posebnog odjeljenja za digitalizaciju ili zapošljavanje stručnjaka za digitalizaciju.' => '2',
								'Primjena inovativnih metodologija (design thinking, lean, agile, customer journey itd).' => '3',
								'Primjena inovativnih tehnologija (npr. Cloud tehnologije za povećanje fleksibilnosti, skalabilnosti i pristupa podacima, korišćenje analitike podataka, jačanje sajber bezbjednosti, upotreba vještačke inteligencije itd.)' => '3',
								'Edukacija zaposlenih.' => '2',
								'Angažovanje spoljnih savjetnika.' => '1',
								'Uvođenje digitalnog marketinga i praćenja zadovoljstva korisnika.' => '2',
								'Ništa od navedenog.' => '0',
								'Ne znam.' => '0',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da64b22c570',
						),
						array(
							'key' => 'field_65da666557237',
							'label' => 'Koje aktivnosti planirate provesti ili smatrate da bi bilo potrebno provesti u cilju primjene digitalne transformacije u kompaniji? (Možete izabrati jedan ili više odgovora)',
							'name' => 'koje_aktivnosti_planirate_provesti_ili_smatrate_da_bi_bilo_potrebno_provesti_u_cilju_primjene_digitalne_transformacije_u_kompaniji_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Izrada analize stanja: prepoznate su oblasti poslovanja koje se mogu unaprijediti digitalizacijom.' => '1',
								'Izrada strateškog plana digitalne transformacije.' => '2',
								'Prilagođavanje poslovnog modela digitalnoj ekonomiji.' => '3',
								'Partnerstva sa drugim kompanijama ili organizacijama radi iskorišćenja novih tehnologija.' => '2',
								'Ulaganje u digitalnu infrastrukturu (oprema i softveri).' => '1',
								'Razvoj i/ili uvođenje novih proizvoda/usluga sa digitalnim elementima.' => '2',
								'Stvaranje posebnog odjeljenja za digitalizaciju ili zapošljavanje stručnjaka za digitalizaciju.' => '2',
								'Primjena inovativnih metodologija (design thinking, lean, agile, customer journey itd).' => '3',
								'Primjena inovativnih tehnologija (npr. Cloud tehnologije za povećanje fleksibilnosti, skalabilnosti i pristupa podacima, korišćenje analitike podataka, jačanje sajber bezbjednosti kompanije, upotreba vještačke inteligencije itd.)' => '3',
								'Edukacija zaposlenih.' => '2',
								'Angažovanje spoljnih savjetnika.' => '1',
								'Uvođenje digitalnog marketinga i praćenja zadovoljstva korisnika.' => '2',
								'Ništa od navedenog.' => '0',
								'Ne znam.' => '0',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da64b22c570',
						),
						array(
							'key' => 'field_65f31a1652788',
							'label' => 'Kako primjenjujete vještačku inteligenciju u poslovanju? (Možete izabrati jedan odgovor)',
							'name' => 'kako_primjenjujete_vjestacku_inteligenciju_u_poslovanju_mozete_izabrati_jedan_odgovor',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Zaposleni u svom u svom radu zazvijaju modele vještačke inteligencije u skladu sa poslovnim potrebama' => '3',
								'Zaposleni koriste vještačku ineligenciju pri obradi podataka i kreiranju izvještaja' => '3',
								'Rukovodstvo ima razvijenu svijest o mogućnostima vještačke inteligencije i primjeni u poslovanju' => '1',
								'Rukovodstvo nema razvijenu svijest o mogućnostima vještačke inteligencije' => '0',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da64b22c570',
						),
						array(
							'key' => 'field_65da678acac27',
							'label' => 'Kako se rukovodstvo odnosi prema inovacijama u kompaniji? (Možete izabrati jedan odgovor)',
							'name' => 'kako_se_rukovodstvo_odnosi_prema_inovacijama_u_kompaniji_mozete_izabrati_jedan_odgovor',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Najviše rukovodstvo daje jasne smjernice za sve faze procesa inovacije.' => '3',
								'Rukovodstvo je upućeno u projekte inovacija.' => '2',
								'Najviše, srednje i projektno rukovodstvo djeluju usklađeno u upravljanju inovativnim aktivnostima.' => '2',
								'Zaposlenima su organizovane obuke o inovacijama.' => '2',
								'Zaposleni imaju benificije ukoliko dokažu inovativnost, kreativnost u radu i/ili vještine rješavanja problema.' => '3',
								'Ništa od navedenog' => '0',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da64b22c570',
						),
						array(
							'key' => 'field_65da69b7cac28',
							'label' => 'Na koje područje u kompaniji će digitalna transformacija imati najveći uticaj? (Možete izabrati jedan ili više odgovora)',
							'name' => 'na_koje_podrucje_u_kompaniji_ce_digitalna_transformacija_imati_najveci_uticaj_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Na poslovni model' => '2',
								'Na kulturu i efikasnost zaposlenih' => '2',
								'Na zadovoljstvo zaposlenih' => '2',
								'Na infrastrukturu (automatizacija)' => '1',
								'Na produktivnost' => '1',
								'Na kvalitet proizvoda ili ponude' => '2',
								'Na odnos sa kupcima' => '2',
								'Na brzinu izlaska na tržište' => '2',
								'Na donošenje poslovnih odluka' => '2',
								'Na smanjenje troškova' => '1',
								'Na konkurentnost' => '2',
								'Na inovativnost kompanije' => '3',
								'Ništa od navedenog' => '0',
								'Ne znam' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da64b22c570',
						),
						array(
							'key' => 'field_65da69dae06f8',
							'label' => 'Šta je prioritet kojem je potrebno posvetiti najviše resursa u naredne dvije godine? (Možete izabrati jedan ili više odgovora)',
							'name' => 'sta_je_prioritet_kojem_je_potrebno_posvetiti_najvise_resursa_u_naredne_dvije_godine_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Bolja informisanost rukovodstva.' => '1',
								'Manje grešaka u radu zaposlenih.' => '1',
								'Bolja komunikacija unutar kolektiva.' => '2',
								'Efikasan sistem kreiranja, praćenja i čuvanja dokumenata.' => '2',
								'Optimizovano korišćenje postojećih softverskih rješenja.' => '3',
								'Korišćenje novih kanala komunikacije sa kupcima.' => '3',
								'Jačanje brenda.' => '3',
								'Povećanje stepena fleksibilnosti u dizajniranju ponude.' => '3',
								'Sistemski pristup on-line marketingu.' => '2',
								'Dodavanje digitalnih mogućnosti proizvodima/uslugama.' => '3',
								'Sajber bezbjednost.' => '2',
								'Ništa od navedenog.' => '0',
								'Ne znam.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da64b22c570',
						),
					),
				),
				array(
					'key' => 'field_65da6b87cfece',
					'label' => 'PROCES (oblast P)',
					'name' => 'proces_oblast_p',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65da6ba0cfecf',
							'label' => 'Koje digitalne tehnologije trenutno koristite u kompaniji? (Možete izabrati jedan ili više odgovora)',
							'name' => 'koje_digitalne_tehnologije_trenutno_koristite_u_kompaniji_mozete_izabrati_jedan_ili_vise_odgovora_',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Softver za planiranje i upravljanje poslovnim resursima (ERP)' => '3',
								'Softver za računovodstvo i upravljanje finansijama' => '2',
								'Softver za upravljanje odnosima sa klijentima (CRM)' => '2',
								'Sistemi za upravljanje projektima (PMT)' => '2',
								'Sistemi za upravljanje zalihama (IMS)' => '2',
								'Alati za automatizaciju marketinga' => '2',
								'Kancelarijski paketi (Microsoft Office i slični)' => '1',
								'Alati za komunikaciju i saradnju (npr. Microsoft Teams, Zoom...)' => '2',
								'Kompjuterski potpomognut dizajn (CAD)' => '2',
								'Softver za unošenje usluge (npr. evidencija radnog vremena, platni spisak, upravljanje resursima)' => '2',
								'Softver specifičan za industriju (modnu, automobilsku, farmaceutsku, itd.)' => '2',
								'Softveri za analitiku (BIT)' => '3',
								'Program lojalnosti' => '1',
								'Ništa od navedenog' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da6b87cfece',
						),
						array(
							'key' => 'field_65da6bd592de0',
							'label' => 'Koje od usluga eUprave koristite? (Možete izabrati jedan ili više odgovora)',
							'name' => 'koje_od_usluga_euprave_koristite_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'eusluge Poreske uprave Republike Srpske' => '2',
								'eusluge Uprave za indirektno oporezivanje BiH' => '2',
								'eusluge lokalne uprave' => '2',
								'elektronska plaćanja banke' => '1',
								'Ništa od navedenog' => '0',
								'Ne znam' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da6b87cfece',
						),
						array(
							'key' => 'field_65da7363cab51',
							'label' => 'Na koji način pratite i upravljate inovacijama? (Možete izabrati jedan ili više odgovora)',
							'name' => 'na_koji_nacin_pratite_i_upravljate_inovacijama_mozete_izabrati_jedan_ili_vise_odgovora_',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Ručno pomoću tabela upravljamo i pratimo aktivnosti inoviranja.' => '1',
								'Imamo proceduru upravljanja inovacijama.' => '2',
								'Za upravljanje inovacijama se koriste potpuno automatizovani alati zasnovani na podacima.' => '3',
								'Organizacija ima skup alata u svakoj fazi procesa inovacije – od upravljanja idejama, preko razvoja i implementacije novih ideja do praćenja tržišta.' => '3',
								'Postoji sistem nagrađivanja i priznavanja inovativnosti kod zaposlenih.' => '2',
								'Ništa od navedenog.' => '0',
								'Ne znam.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da6b87cfece',
						),
						array(
							'key' => 'field_65da7380f2093',
							'label' => 'Da li su procesi automatizovani? (uzmite u obzir proizvodnju/pružanje usluga i/ili administraciju i/ili građevinske objekte) (Možete izabrati jedan ili više odgovora) ',
							'name' => 'da_li_su_procesi_automatizovani_uzmite_u_obzir_proizvodnjupruzanje_usluga_iili_administraciju_iili_gradevinske_objekte_mozete_izabrati_jedan_ili_vise_odgovora ',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Procesi nisu automatizovani i obavljaju ih samo zaposleni.' => '0',
								'Procesi su djelimično automatizovani, ali i dalje zahtjevaju značajnu intervenciju zaposlenih.' => '1',
								'Procesi su automatizovani, ali zahtjevaju intervenciju zaposlenih za pokretanje i završetak svakog procesa.' => '2',
								'Procesi su potpuno automatizovani. Intervencija zaposlenih je neophodna samo u slučaju neplaniranih događaja.' => '3',
								'Procesi su potpuno automatizovani, moguća je fleksibilna rekonfiguracija parametara i zadataka, a neplanirani događaji zahtevaju manju intervenciju zaposlenih.' => '3',
								'Procesi su potpuno automatizovani, fleksibilni i ne zahtevaju intervenciju zaposlenih. Sistemi upravljanja procesima su integrisani sa svim sistemima preduzeća, što omogućava saradnju između različitih odjeljenja ili eksternih partnera.' => '3',
								'Nije primjenjivo u našem poslovanju.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da6b87cfece',
						),
						array(
							'key' => 'field_65f30fdbf30b5',
							'label' => 'Da li pratite stanje mašina i kako provodite održavanje? (Možete izabrati jedan odgovor)',
							'name' => 'da_li_pratite_stanje_masina_i_kako_provodite_odrzavanje_mozete_izabrati_jedan_odgovor',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Preduzeće ima organizovanu službu/tim koja je zadužena za održavanje opreme u privrednom društvu. Zaposleni u Službi imaju jasno definisane uloge i odgovornosti.' => '3',
								'Preduzeće koristi softver za praćenje održavanja mašina i postrojenja.' => '3',
								'Preduzeće ima definisan plan praćenja stanja mašina za koji su odgovorni rukovaoci mašinama. Održavanje mašina obavljaju eksterno angažovani majstori.' => '1',
								'Preduzeće prati stanje mašina po potrebi, odnosno u zavisnosti od zastoja u proizvodnom procesu.' => '0',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da6b87cfece',
						),
						array(
							'key' => 'field_65da73aa562e7',
							'label' => 'Kako dizajnirate proizvode? (Možete izabrati jedan ili više odgovora) ',
							'name' => 'kako_dizajnirate_proizvode_mozete_izabrati_jedan_ili_vise_odgovora ',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Kompjuterski potpomognut dizajn (CAD - Computer Added Design) se ne koristi u dizajnu proizvoda.' => '0',
								'CAD se koristi za projektovanje proizvoda.' => '1',
								'Proizvodi su dizajnirani pomoću CAD-a, a izrada prototipa se vrši pomoću 3D skenera i štampača.' => '2',
								'Proizvodi su dizajnirani pomoću CAD-a, a pri izradi prototipa se koristi virtuelna realnost i/ili umjetna inteligencija.' => '3',
								'Proizvodi su opremljeni senzorima i ugrađenim sistemima koji omogućavaju prikupljanje i analizu podataka iz faze korišćenja proizvoda u realnom vremenu.' => '3',
								'Proizvodi imaju svoj digitalni ekvivalent integrisan sa podacima sa senzora ugrađenih u fizički proizvod, što omogućava simulaciju procesa korišćenja.' => '3',
								'Ništa od navedenog.' => '0',
								'Nije primjenjivo u našem poslovanju.' => '0',
								'Ne znam.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da6b87cfece',
						),
						array(
							'key' => 'field_65f3106c01001',
							'label' => 'Ukoliko preduzeće koristi 3D projektovanje u razvoju novog proizvoda, da li imate vlastite uređaje za projekotvanje? (Možete izabrati jedan odgovor)',
							'name' => 'ukoliko_preduzece_koristi_3d_projektovanje_u_razvoju_novog_proizvoda_da_li_imate_vlastite_uredaje_za_projekotvanje_mozete_izabrati_jedan_odgovor',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Da, preduzeće podjeduje 3D uređaje za projektovanje novih proizvoda.' => '3',
								'Ne, pri projektovanju novih proizvoda, koristimo usluge drugog preduzeća pri 3D projektovanju.' => '2',
								'Ne koristimo 3D modelovanje, ali ramišljamo da počnemo koristiti 3D modelovanje u razvoju novih proizvoda.' => '1',
								'Ne koristimo 3D modelovanje pri razvoju novih proizvoda i trenutno nemamo potrebu za korištenjem istog.' => '0',
								'Nije primjenjivo u našem poslovanju.' => '0',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_65da6b87cfece',
						),
					),
				),
				array(
					'key' => 'field_65da73c2da694',
					'label' => 'LJUDSKI RESURSI (oblast H)',
					'name' => 'ljudski_resursi_oblast_h',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65da73f3da695',
							'label' => 'Kako se provodi obuka za pripremu zaposlenih za digitalnu transformaciju? (Možete izabrati jedan ili više odgovora)',
							'name' => 'kako_se_provodi_obuka_za_pripremu_zaposlenih_za_digitalnu_transformaciju_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Ne organizujemo obuke zaposlenih.' => '0',
								'Odabrane zaposlene obučavamo kada to zahtjeva tržište i situacija u kompaniji.' => '2',
								'Zaposleni povremeno pohađaju eksterne obuke koje besplatno nudi Privredna komora.' => '1',
								'Zaposlenima povremeno finansiramo eksterne obuke koje nude za to specijalizovane organizacije.' => '1',
								'Imamo program obuke koji se fokusira na stalni razvoj vještina zaposlenih.' => '3',
								'Imamo program obuke prilagođen potrebama kompanije a koji služi i za pronalaženje i razvoj talenata.' => '3',
								'Ništa od navedenog.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da73c2da694',
						),
					),
				),
				array(
					'key' => 'field_65da74168e45c',
					'label' => 'MARKETING (oblast M)',
					'name' => 'marketing_oblast_m',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65da74278e45d',
							'label' => 'Koje od navedenih digitalnih kanala koristite za prodaju, komunikaciju i/ili građenje odnosa sa klijentima? (Možete izabrati jedan ili više odgovora) ',
							'name' => 'koje_od_navedenih_digitalnih_kanala_koristite_za_prodaju_komunikaciju_iili_gradenje_odnosa_sa_klijentima_mozete_izabrati_jedan_ili_vise_odgovora ',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Prodaja se obavlja samo tradicionalnim kanalima, a tehnološki nivo ne dozvoljava personalizaciju sadržaja, kanala komunikacije, ponude i proizvoda.' => '0',
								'Internet stranica kompanije.' => '1',
								'Internet prodavnica kompanije.' => '2',
								'Bilten koji se šalje elektronskom poštom.' => '1',
								'Društvene mreže (Facebook, Instagram, Twiter, LinkedIn, itd.)' => '2',
								'Platforme za prodaju (Amazon, eBay, Olx itd.)' => '3',
								'Video platforme (Youtube, Vimeo, itd.)' => '2',
								'Klijent je uključen u ko-kreaciju proizvoda tako što daje informacije i smjernice za razvoj i dizajn novih proizvoda/usluga.' => '3',
								'Ne znam.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da74168e45c',
						),
						array(
							'key' => 'field_65da7443e7599',
							'label' => 'U kojoj mjeri generalno prikupljate i koristite podatke (o kupcima, dobavljačima i drugim partnerima) u svrhu razvoja i transformacije poslovanja kompanije?  (Možete izabrati jedan ili više odgovora)',
							'name' => 'u_kojoj_mjeri_generalno_prikupljate_i_koristite_podatke_o_kupcima_dobavljacima_i_drugim_partnerima_u_svrhu_razvoja_i_transformacije_poslovanja_kompanije _mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Ne prikupljamo, niti koristimo podatke.' => '0',
								'Prikupljamo, ali ne koristimo podatke.' => '0',
								'Podatke prikupljamo i koristimo za segmentaciju tržišta i stvaranje personalizovanog odnosa sa kupcima.' => '2',
								'Podatke prikupljamo i koristimo za efikasnije upravljanje operacijama i optimizaciju poslovnih procesa.' => '3',
								'Podatke prikupljamo i koristimo za razvoj novih proizvoda i usluga.' => '3',
								'Ne znam.' => '0',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da74168e45c',
						),
					),
				),
				array(
					'key' => 'field_65da745bc49f5',
					'label' => 'FINANSIJE (oblast F)',
					'name' => 'finansije_oblast_f',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65da746fc49f6',
							'label' => 'Šta sprečava veća ulaganja u digitalnu transformaciju u kompaniji? (Možete izabrati jedan ili više odgovora)',
							'name' => 'sta_sprecava_veca_ulaganja_u_digitalnu_transformaciju_u_kompaniji_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Nedostatak finansijskih sredstava.' => 'Nedostatak finansijskih sredstava.',
								'Nedostatak vizije i sveobuhvatne digitalne strategije.' => 'Nedostatak vizije i sveobuhvatne digitalne strategije.',
								'Prevelika fokusiranost na druge, trenutne prioritete.' => 'Prevelika fokusiranost na druge, trenutne prioritete.',
								'Nedostatak znanja, liderskih vještina i ekspertize u primjeni novih tehnologija.' => 'Nedostatak znanja, liderskih vještina i ekspertize u primjeni novih tehnologija.',
								'Nedostatak podrške zaposlenih i kultura koja nije podložna promjenama.' => 'Nedostatak podrške zaposlenih i kultura koja nije podložna promjenama.',
								'Nedostatak vremena i neizvjesnost ishoda.' => 'Nedostatak vremena i neizvjesnost ishoda.',
								'Bojazan od radikalnih promjena/odluka i neizvjesnost ishoda.' => 'Bojazan od radikalnih promjena/odluka i neizvjesnost ishoda.',
								'Rigidan sistem i birokratija.' => 'Rigidan sistem i birokratija.',
								'Ne primjenjujemo digitalnu transformaciju u kompaniji.' => 'Ne primjenjujemo digitalnu transformaciju u kompaniji.',
								'Ne znam.' => 'Ne znam.',
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da745bc49f5',
						),
						array(
							'key' => 'field_65da7486c49f7',
							'label' => 'Da li ste učestvovali u nekim od programa podrške digitalnoj transformaciji privrednih društava? (Možete izabrati jedan ili više odgovora)',
							'name' => 'da_li_ste_ucestvovali_u_nekim_od_programa_podrske_digitalnoj_transformaciji_privrednih_drustava_mozete_izabrati_jedan_ili_vise_odgovora',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Učestvovali smo u najmanje jednoj regionalnoj inicijativi partnerskih kompanija.' => '1',
								'Učestvovali smo u najmanje jednom programu stranih donatora (npr. GIZ, USAID, strane vlade i sl.).' =>	'2',
								'Kandidovali smo projekat na program podrške digitalizaciji koji provodi Ministarstvo privrede i preduzetništva Republike Srpske.' => '2',
								'Koristili smo savjetodavne usluge Centra za digitalnu transformaciju PKRS.	' => '3',
								'Koristili smo podršku lokalne uprave za digitalizaciju.' => '2',
								'Koristili smo usluge lokalnih agencija za razvoj i/ili učestvovali u njihovim projektima digitalizacije.' => '1',
								'Aktivnosti digitalizacije provode zaposleni, a finansiramo ih iz kreditnih sredstava.' => '2',
								'Aktivnosti digitalizacije provode zaposleni, a finansiramo ih vlastitim sredstvima.' => '3',
								'Ništa od navedenog.	' => '0',
								'Ne znam.' => '0'
							),
							'default_value' => array(),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 0,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
							'parent_repeater' => 'field_65da745bc49f5',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		));
	}
}
