<?php

namespace InnDigit\Components\Pdf;

class Constants
{
    public static $comments = [
        'S1' => 'Odgovori iz InnDigit Alata upućuju na to da je kompanija u dijelu strateškog pristupa procesu digitalne transformacije na niskom nivou. Ukoliko vizija digitalne transformacije nije razvijena i najviše rukovodstvo samo deklarativno podržava digitalnu transformaciju, potrebno je motivisati donošenje strateških odluka na ovom polju, te započeti proces digitalne transformacije. Nakon definisanja vizije i ciljeva digitalnog puta, slijedi usklađivanje tih ciljeva sa poslovnim strategijama.
        Razvijena sveobuhvatna digitalna strategija ključna je za postizanje uspjeha. Ovo uključuje analizu trenutnih procesa, identifikaciju ključnih područja za digitalizaciju i planiranje koraka ka implementaciji. 
        Vrijeme je za izrade mape puta digitalne transformacije. U saradnji sa Centrom za digitalnu transformaciju Privredne komore će ovaj plan biti najlakše izrađen, a zatim i proveden.',
        'S2' => 'Odgovori iz InnDigit Alata upućuju na to da je kompanija u dijelu strateškog pristupa procesu digitalne transformacije na srednjem nivou. Ukoliko je vizija digitalne transformacije u razradi a najviše rukovodstvo aktivno podržava digitalnu transformaciju, za potpunu predanost je potrebno imati još samo ciljeve koji se usklađuju s poslovnim strategijama.
        Razvijena sveobuhvatna digitalna strategija ključna je za postizanje uspjeha. Ovo uključuje analizu trenutnih procesa, identifikaciju ključnih područja za digitalizaciju i planiranje koraka ka implementaciji. 
        Podršku za izradu mape puta digitalne transformacije i implementaciju projekata digitalizacije poslovanja pruža Centar za digitalnu transformaciju Privredne komore Republike Srpske.',
        'S3' => 'Odgovori iz InnDigit Alata upućuju na to da je kompanija u dijelu strateškog pristupa procesu digitalne transformacije na naprednom nivou. Ukoliko je vizija digitalne transformacije razvijena i najviše rukovodstvo aktivno podržava digitalnu transformaciju, za potpunu predanost je potrebno imati još samo ciljeve koji se usklađuju s poslovnim strategijama.
        Razvijena sveobuhvatna digitalna strategija ključna je za postizanje uspjeha. Ovo uključuje analizu trenutnih procesa, identifikaciju ključnih područja za digitalizaciju i planiranje koraka ka implementaciji. 
        Ukoliko je prošlo više od dvije godine od poslednje izrade mape puta, u saradnji sa Centrom za digitalnu transformaciju Privredne komore će ovaj plan biti najlakše ažuriran. ',
        'P1' => 'Rezultati analize odgovora upućuju na to da je kompanija u dijelu digitalne transformacije poslovnog procesa na niskom nivou. 
        Investiranje u modernu tehnološku infrastrukturu okosnica je digitalne transformacije kompanije. To je i najvidljiviji dio, koji dodatno motiviše kolektiv na stalno unapređenje. Ukoliko kompanija razmotri mogućnosti upotrebe računarstva u oblaku, naprednih analitičkih alata i vještačke inteligencije u poslovanju te odluči da što više automatizuje procese, učiniće mnogo za svoju održivost. Centar za digitalnu transformaciju ima obučene konsultante koji, nakon donesene odluke o unapređenju procesa, kompaniji pomažu da strukturisano i na najefikasniji način primjeni nova rješenja.',
        'P2' => 'Rezultati analize odgovora upućuju na to da je kompanija u dijelu digitalne transformacije poslovnog procesa na srednjem nivou. 
        Investiranje u modernu tehnološku infrastrukturu okosnica je digitalne transformacije kompanije. To je i najvidljiviji dio, koji dodatno motiviše kolektiv na stalno unapređenje. Ukoliko kompanija djelimično korisiti računarstvo u oblaku, napredne analitičke alate i vještačku inteligenciju u poslovanju te odluči da dalje automatizuje procese, učiniće mnogo za svoju održivost. Centar za digitalnu transformaciju ima obučene konsultante koji kompaniji pomažu da strukturisano i na najefikasniji način primjeni nova rješenja za unapređenje procesa. Osim toga, uz podršku CDT-a brže se dolazi do informacija o kvalitetnim domaćim podugovaračima te se cijeli proces transformacije neprestano nadzire i usklađuje sa potrebama kompanije.',
        'P3' => 'Rezultati analize odgovora upućuju na to da je kompanija u dijelu digitalne transformacije poslovnog procesa na naprednom nivou.
        Investiranje u modernu tehnološku infrastrukturu okosnica je digitalne transformacije kompanije. To je i najvidljiviji dio, koji dodatno motiviše kolektiv na stalno unapređenje. Kompanije koje koriste računarstvo u oblaku, napredne analitičke alate, vještačku inteligenciju i automatizaciju procesa, učinile su mnogo za svoju održivost. Uz angažman u akcijama Centra za digitalnu transformaciju i prenos svojih iskustava drugim domaćim privrednim subjektima, možete učiniti mnogo i za održivost privrede i cijelog društva.',
        'H1' => 'Odgovori iz InnDigit Alata upućuju na to da su akcije kompanije u vezi razvoja vještina zaposlenih za proces digitalne transformacije ocijenjene niskom ocjenom.
        To znači da je kompanija nije prepoznala značaj osnaživanja zaposlenih digitalnim vještinama za uspjeh transformacije. Edukacija i trening zaposlenih za korišćenje novih tehnologija i alata ključni su za dobar efekat digitalne transformacije kompanije. Centar za digitalnu transformaciju veliki dio svojih kapaciteta posvećuje akcijama koje se tiču razvoja znanja donosioca odluka i svih članova kolektiva domaćih kompanija u vezi sa digitalnim vještinama i tržišnim trendovima.',
        'H2' => 'Odgovori iz InnDigit Alata upućuju na to da su akcije kompanije u vezi razvoja vještina zaposlenih za proces digitalne transformacije ocijenjene srednjom ocjenom.
        To znači da je kompanija prepoznala značaj osnaživanja zaposlenih digitalnim vještinama za uspjeh transformacije ali da izostaje predanost ovom zadatku i planski pristup. Edukacija i trening zaposlenih za korišćenje novih tehnologija i alata ključni su za dobar efekat digitalne transformacije kompanije. Centar za digitalnu transformaciju veliki dio svojih kapaciteta posvećuje akcijama koje se tiču razvoja znanja donosioca odluka i svih članova kolektiva domaćih kompanija u vezi sa digitalnim vještinama i tržišnim trendovima.',
        'H3' => 'Odgovori iz InnDigit Alata upućuju na to da su akcije kompanije u vezi razvoja vještina zaposlenih za proces digitalne transformacije ocijenjene visokom ocjenom.
        To znači da je kompanija prepoznala značaj osnaživanja zaposlenih digitalnim vještinama za uspjeh transformacije. Edukacija i trening zaposlenih pri uvođenju novih tehnologija i alata su ključni za uspjeh procesa digitalne transformacije. Centar za digitalnu transformaciju veliki dio svojih kapaciteta posvećuje akcijama koje se tiču razvoja znanja donosioca odluka i svih članova kolektiva domaćih kompanija u vezi sa digitalnim vještinama i tržišnim trendovima.',
        'M1' => 'Odgovori iz oblasti Marketing InnDigit Alata ukazuju da je kompanija u ovoj oblasti digitalne transformacije postiže niske rezultate.
        To znači da je kompanija nije prepoznala da digitalna transformacija marketinga može značajno unaprijediti efikasnost komunikacije s ciljnim auditorijumom, povećati angažovanje kupaca i poboljšati ukupno iskustvo kupovine.
        Savremeni alati u ovoj oblasti kompanijama pomažu da bolje razumiju profil ciljne publike i ponude personalizovan sadržaj koji odgovara potrebama svakog pojedinačnog kupca. Upotreba rješenja za automatizaciju marketinga olakšava proces, štedi vrijeme i povećava efikasnost. Vještačka inteligencija je omogućila mnogo bolju analizu podataka, te predviđanje ponašanja kupaca. Ostale oblasti na kojima kompanija treba da djeluje pri digitalnoj transformaciji svog marketinga su društvene mreže, mjerenje performansi, mobilni marketing, razvoj online zajednice...',
        'M2' => 'Odgovori iz oblasti Marketing InnDigit Alata ukazuju da je kompanija u ovoj oblasti digitalne transformacije postiže srednje rezultate.
        To znači da kompanija nije postigla svoj maksimum pri upotrebi rješenja za digitalnu transformaciju marketinga, što može značajno unaprijediti efikasnost komunikacije s ciljnim auditorijumom, povećati angažovanje kupaca i poboljšati ukupno iskustvo kupovine.
        Savremeni alati u ovoj oblasti kompanijama pomažu da bolje razumiju profil ciljne publike i ponude personalizovan sadržaj koji odgovara potrebama svakog pojedinačnog kupca. Upotreba rješenja za automatizaciju marketinga olakšava proces, štedi vrijeme i povećava efikasnost. Vještačka inteligencija je omogućila mnogo bolju analizu podataka, te predviđanje ponašanja kupaca. Ostale oblasti na kojima kompanija treba da djeluje pri digitalnoj transformaciji svog marketinga su društvene mreže, mjerenje performansi, mobilni marketing, razvoj online zajednice...',
        'M3' => 'Odgovori iz oblasti Marketing InnDigit Alata ukazuju da je kompanija u ovoj oblasti digitalne transformacije postiže napredne rezultate.
        To znači da je kompanija prepoznala da digitalna transformacija marketinga može značajno unaprijediti efikasnost komunikacije s ciljnim auditorijumom, povećati angažovanje kupaca i poboljšati ukupno iskustvo kupovine.
        Digitalna transformacija marketinga je kontinuiran proces, stoga je važno pratiti nove tehnologije i trendove kako bi organizacija ostala konkurentna i bila sposobna da zadovoljava promjenljive potrebe kupca.',
        'F1' => 'InnDigit Alat procjenjuje nizak nivo zrelosti za digitalnu transformaciju kompanije u oblasti finansija.
        Prema tome, kompanija nije uspješna u upotrebi savremenih alata za računovodstvo i finansije, te ne koristi sve mogućnosti kada su u pitanju načini i izvori finansiranja akcija digitalne transformacije u kompaniji.
        InfoBiz je platforma Privredne komore Republike Srpske na kojoj su ažurne informacije u vezi sa ekosistemom za digitalnu transformaciju naših privrednih društava <a href=https://infobiz.komorars.ba/>infobiz.komorars.ba</a>',
        'F2' => 'InnDigit Alat procjenjuje srednji nivo zrelosti za digitalnu transformaciju kompanije u oblasti finansija.
        Prema tome, kompanija je djelimično uspješna u upotrebi savremenih alata za računovodstvo i finansije, te ne koristi sve mogućnosti kada su u pitanju načini i izvori finansiranja akcija digitalne transformacije u kompaniji.
        InfoBiz je platforma Privredne komore Republike Srpske na kojoj su ažurne informacije u vezi sa ekosistemom za digitalnu transformaciju naših privrednih društava https://infobiz.komorars.ba/',
        'F3' => 'InnDigit Alat procjenjuje napredni nivo zrelosti za digitalnu transformaciju kompanije u oblasti finansija.
        Prema tome, kompanija je uspješna u upotrebi savremenih alata za računovodstvo i finansije, te na optimalno koristi načine finansiranja akcija digitalne transformacije u kompaniji.
        InfoBiz je platforma Privredne komore Republike Srpske na kojoj su ažurne informacije u vezi sa ekosistemom za digitalnu transformaciju naših privrednih društava <a href=https://infobiz.komorars.ba/>infobiz.komorars.ba</a>'
    ];
}
